### PR TITLE
TS cover replacement

### PR DESCRIPTION
**Pull request by macintux**
In support of basho/riak_kv#1425 and more directly basho/riak_test#1078. Support the replacement of coverage chunks by clients.

### CODE REVIEW

**Comment by hmmr** [comment]
+1 285d6d7

I still suggest you squash the two commits and re-push.

**Comment by macintux** [comment]
Squashed.

**Comment by hmmr** [comment]
+1 6d425b3

**Comment by macintux** [comment]
Bors testing is hung. YOLOmerged

**Pull request merged**
