### PR TITLE
Feature/erlang 20 bryan enhanced

### PR DESCRIPTION
**Pull request by ghost**
So @manifest modified the rebar.config to make it work with Erlang 20. On my system it wouldn't run the eunit because in Erlang 20 `-compiler(export_all)` produces warnings, and rebar.config defines warnings as build errors. So I've explicitly exported the necessary functions. I've tested this with `kerl` erlang versions:

* 16b02-basho10
* 17.5
* 18.3
* 19.3
* 20.1

Tested with:

```
rm -rf .eunit ebin deps && ./rebar get-deps && ./rebar compile && ./rebar eunit
```
Eunit tests passed.

### CODE REVIEW

**Comment by russelldb** [comment]
WFM, but before I +1, can I ask if there is a way to ignore this warning as a compiler option, since it is used often in Riak code, especially in `ifdef(test)` blocks

**Comment by ghost** [comment]
@russelldb - I could not find a way to do so, short of removing the rebar configuration which makes warnings as build errors. Probably best practice to not use `export_all` anyway.

**Comment by russelldb** [comment]
Not going to argue best practice wrt `export_all`, but if this the best way to get around the warning, then +1 from me.

**Comment by ghost** [comment]
Ta @russelldb

**Comment by martincox** [comment]
Stumbled across this whilst looking into something else related. Can specify ```-compile(nowarn_export_all)``` to suppress compiler errors. Bit quicker than exporting all functions, which I guess is fine for test modules.

**Comment by ghost** [comment]
What do you want to pass this test case? Make all public by default and
ignore error on newer erlang version? Or stick with what we've got?

**Comment by bryanhuntesl** [comment]
develop is what's going to be 3.0 in the future, is that the strategy?

**Comment by martincox** [comment]
Definitely stick with what we've got I guess. Was just mentioning as I was looking into making another repo support OTP20.

**Pull request merged**
