### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by seanmcevoy**
Added new timeout mechanism and some new stats collection.
Intended to be fully backward compatible.
See overload_test & stats_demo test functions.

### CODE REVIEW

**Comment by lukebakken** [comment]
Hi,

Thank you for taking the time to contribute to this project. This PR represents too many changes to accept in one pull request. Would it be possible to break this up into smaller changes, each with its own set of tests to go with it?

Also, the changes should be against `master` and not another branch.

**Comment by seanmcevoy** [comment]
Hi Luke,
I'm working on the changes you suggested, was hoping to get them finished
over the weekend but it looks like they'll go into next week.
Will get back to you again when I make the new pull requests.
//Sean.

**Comment by seanmcevoy** [comment]
Hi Luke,

I just made 2 pull requests for the erlang client:
https://github.com/basho/riak-erlang-client/pull/251
https://github.com/basho/riak-erlang-client/pull/252

251 adds a new timeout mechanism, it's fully backward compatible with the
old timeouts and has two unit tests plus one demo test showing it's
advantage over the old mechanism.

252 is built on top of 251 and adds some statistics functionality which has
been designed to be ignorable, so is again backward compatible. The
presentation of the stats is very low-level but was sufficient for our
needs and could be a good base if anyone wants to build a more
sophisticated stats tool on top.

Let me know if you need anything else from me in relation to these changes.
Am happy to contribute what I can :-)

//Sean.

**Comment by lukebakken** [comment]
Superceded by #251 and #252

**Pull request closed without merging**
