### PR TITLE
Support TsCoverageReq

### PR DESCRIPTION
**Pull request by macintux**
WIP. @hmmr will be carrying this set of PRs forward.

Allow coverage queries for TS.

### CODE REVIEW

**Comment by macintux** [comment]
Relies on basho/riak_pb#173

**Comment by lehoff** [comment]
+1

**Comment by hmmr** [comment]
@borshop merge

**Comment by hmmr** [comment]
@borshop merge

**Comment by hmmr** [comment]
@borshop merge

**Pull request merged**
