### PR TITLE
Basic Timeseries Support

### PR DESCRIPTION
**Pull request by bkerley**
This implements weirdly-structured and somewhat-broken Riak time series support in the Erlang client.

# New Modules

* `riakc_timeseries` - Front-end module with high-level user-useful functions; exported functions take a `riakc_pb_socket` pid as an argument.
* `riakc_ts_query_operator` - Encapsulates serialization and deserialization of time series queries
* `riakc_ts_put_operator` - Encapsulates serialization and deserialization of time series put operations

# Changes to Existing Files

* `riakc_pb_socket` - added `tsputresp` and `#tsqueryresp` bodies to `process_response/3`
* `README.md` - a couple marginally-documented slugs I've been pasting into `rebar shell` to "test"
* `rebar.config` - pull in `end-to-end/timeseries` branch that includes time series messages

# Missing

* There are no useful tests.
* `riakc_ts_put_operator:columns_for/1` extremely naïvely assumes you have no column definitions and want to let Riak/your table declaration decide what columns you're submitting. Deferred for number format discussions.
* `riakc_ts_put_operator:cell_for/1` also naïvely guesses the cell type based on the erlang type of the measurement: this is how it works in the Ruby client (that I cribbed from :smirk_cat: ), and probably merits some kind of discussion about how we express both column and cell types among all our clients.

With these caveats, *merging and supporting this might not be a great idea!*

### CODE REVIEW

**Comment by bkerley** [comment]
-1 b229bf2

**Comment by javajolt** [comment]
@bkerley Did you just :-1: your own PR?

**Comment by bkerley** [comment]
I'm under the impression that a :-1: makes it harder to accidentally make B.O.R.S.H.O.P. do a thing.

**Comment by lukebakken** [comment]
Thanks @bkerley. This is superceded by #282

**Pull request closed without merging**
