### PR TITLE
Ensure strings are actually binaries in and out of the client

### PR DESCRIPTION
**Pull request by javajolt**
With TTB encoding we no longer go through PBC which converted strings to binaries for us.  Do this now explicitly on certain fields.

### CODE REVIEW

**Comment by lukebakken** [comment]
@javajolt - how does this relate to #270?

**Comment by javajolt** [comment]
@lukebakken This is a smaller change.  I think Andrei had his own idea about what needing doing so went ahead with a different solution.  His seems to have a much greater scope.  I am simply trying to get existing tests to pass.

**Comment by lukebakken** [comment]
I tested #270 and this PR is definitely needed.

**Comment by lukebakken** [comment]
See #272

**Pull request closed without merging**
