### PR TITLE
Add `node_confirms` option to PUT request

### PR DESCRIPTION
**Pull request by russelldb**
And counter/datatype operations. NOTE: depends on riak-2.2.5
node_confirms feature.

Depends on:
https://github.com/basho/riak_pb/pull/228

Depended on:
https://github.com/basho/riak_kv/pull/1663

### CODE REVIEW

**Comment by russelldb** [comment]
Travis fails because it doesn't know to use the riak_pb branch that this pull request builds on, is there anyway around that? Change the `rebar.config` and then change it back before/after merging?

**Comment by ghost** [comment]
Am I correct in understanding the fail is due to the referenced p/r (riak_kv/riak_pb) not having been merged yet ?

**Comment by russelldb** [comment]
right, but I wonder if we can just tell travis to use the right branch somehow?

**Comment by ghost** [comment]
The only think I could think of would be to send up a .gitconfig with the aproprate aliases in place but that's probably more effort than it's worth. When we get on rebar3, profiles could also be an option;  but again, a lot of effort. I'll try to get the two dependent p/r reviewed today.

**Comment by russelldb** [comment]
merged pb and tada, travis is super-green

**Review by nickkeers — APPROVED** [review]
:+1: Looks fine to me

**Comment by ghost** [comment]
ship-it-squirrel

**Pull request merged**
