### PR TITLE
new API function riakc_ts:list_keys/3

### PR DESCRIPTION
**Pull request by hmmr**
RTS-203.

Depends on https://github.com/basho/riak_kv/pull/1268 and https://github.com/basho/riak_pb/pull/162.

### CODE REVIEW

**Comment by lukebakken** [comment]
+1 from me but someone with more experience should also review.

**Comment by andytill** [comment]
@borshop: retry

**Comment by andytill** [comment]
+1 221271

**Comment by javajolt** [comment]
:+1: ee985f5

**Comment by alexmoore** [comment]
@borshop merge

**Pull request merged**
