### PR TITLE
Fix issues from riak_pb timestamp encoding changes.

### PR DESCRIPTION
**Pull request by alexmoore**
Use different versions of riak_pb_ts_codec:encode_xxxxx since the originals changed. 
Also fixed some specs here and there. 

This depends on basho/riak_pb#164

### CODE REVIEW

**Comment by javajolt** [comment]
:+1: 63d40f2

**Comment by alexmoore** [comment]
@borshop retry

**Comment by javajolt** [comment]
:+1: fc6bab7

**Comment by alexmoore** [comment]
@borshop merge

**Pull request merged**
